### ISSUE TITLE
Some issues with the Panasonic Viera TX-50AW404

### ISSUE THREAD

**Issue by BenGore** [g30r93g/homebridge-panasonic#4]
I‘m not able to switch the tv on (from standby mode).
The tv has native no Plex, no Amazon Video, no YouTube and no HDMI 3, but all of them are shown in Apple Home.
Is it possible that I delete the inputs I don‘t need or is it possible that the Plugin just shows the inputs the tv really has?
Many thanks in advance and thank you for this great plugin!

**Comment by g30r93g** [comment]
Hi! There may be a few settings you need to change on your TV in order to switch it on from standby.
Go to Menu -> Network -> TV Remote App Settings and make sure the following settings are on: 
 • TV Remote
 • Powered On by Apps
 • Networked Standby
It is possible that the TV may not support power on by standby.

I am also aware of the fact that the inputs aren't accurate but I haven't found an endpoint where the inputs are exposed, so I've just set up a few inputs so you can use it to some degree. I am working on adding inputs via the config file and that will come in a future update. You'll also be able to add more apps if you wish.

Hope this resolves any problems you're having!

**Comment by BenGore** [comment]
Thank you for your quick reply.
Unfortunately my tv is not able to receive the „switch on“ command. Not even via the Panasonic Remote Control App.
So I‘m looking fortward for the upcomming releases 
Thank you

**Comment by g30r93g** [comment]
I'll start a new issue containing models that aren't supported.
